### ISSUE TITLE
Compilation fails when trying ormin nimble package

### ISSUE THREAD

**Issue by konqoro** [Araq/ormin#2]
I get this error in my code:
`notesapp.nim(3, 31) Error: cannot open 'notes_model'`
But before that there is another warning:
`fatal: cannot open $USER/.nimble/pkgs/ormin-#head/ormin.nim/notes_model.sql`

**Comment by konqoro** [comment]
It is caused because of a bug in `currentSourcePath()`. If two modules `ormin.nim`:
```
template t*: untyped =
   echo currentSourcePath()
```
and app.nim:
```
import ormin
t()
```
it outputs the first's module path. It works if we call instantiationInfo(-1, true).filename directly.

**Comment by konqoro** [comment]
It is caused because of a bug in `currentSourcePath()`. If two modules `ormin.nim`:
```
template t*: untyped =
   echo currentSourcePath()
```
and app.nim:
```
import ormin
t()
```
it outputs the first's module path. It works if we call instantiationInfo(-1, true).filename directly.

**Comment by konqoro** [comment]
now it fails with: `notesapp.nim(3, 21) Error: in expression '("/home/markedone/nim/src/notesapp.nim", 3)."notes_model"': identifier expected, but found '"notes_model"'`

**Comment by konqoro** [comment]
note that even when reverting the last commit with:
```
import ormin
importModel(sqlite, currentSourcePath(), "notes_model")
```
outputs:
`fatal: cannot open /home/username/nim/src/notesapp.nim/notes_model.sql`

**Comment by Araq** [comment]
Sorry for this rather late reply, but I'm actively working on a good real world Ormin+Karax example that documents its usage (and limitations).

**Comment by konqoro** [comment]
Sure no worries. You have a lot of staff to maintain. Besides I already had a workaround.
