### ISSUE TITLE
Error running  nimble test.

### ISSUE THREAD

**Issue by demianfe** [Araq/ormin#47]
Running `nimble test` produces the following error:

> /Data/devel/projects/external/ormin/tests/tforum.nim(6, 7) template/generic instantiation of `suite` from here
> /Data/devel/projects/external/ormin/tests/tforum.nim(207, 8) template/generic instantiation of `test` from here
> /Data/devel/projects/external/ormin/tests/tforum.nim(215, 20) Error: undeclared identifier: 'lc'
> stack trace: (most recent call last)
> /Data/devel/projects/external/Nim/lib/system/nimscript.nim(401, 18)
> /Data/devel/projects/external/ormin/config.nims(53, 12) tcommonTask
> /Data/devel/projects/external/Nim/lib/system/nimscript.nim(280, 7) selfExec
> /Data/devel/projects/external/Nim/lib/system/nimscript.nim(280, 7) Error: unhandled exception: FAILED: /Data/devel/projects/external/Nim/bin/nim run  /Data/devel/projects/external/ormin/tests/tforum [OSError]
> stack trace: (most recent call last)
> /Data/Variable/tmp/nimblecache/nimscriptapi.nim(165, 16)
> /Data/devel/projects/external/ormin/ormin_4545.nims(25, 12) testTask
> /Data/devel/projects/external/Nim/lib/system/nimscript.nim(280, 7) selfExec
> /Data/devel/projects/external/Nim/lib/system/nimscript.nim(280, 7) Error: unhandled exception: FAILED: /Data/devel/projects/external/Nim/bin/nim tcommon [OSError]
>      Error: Exception raised during nimble script execution

**Comment by huaxk** [comment]
Maybe you're using nim version 1.2，the test code use lc of nim version 1.0.6, should be fixed.
